services:
  - type: web
    name: frigoninja
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
        value: "mongodb+srv://f:miPassword123@cluster0.89joi35.mongodb.net/frigoninja?retryWrites=true&w=majority"
      - key: MONGO_DB
        value: frigoninja
